(() => {
  const menuButton=document.querySelector('.menu-button'), navLinks=document.querySelector('.nav-links');
  if(menuButton&&navLinks){menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));navLinks.classList.toggle('is-open',!open)});navLinks.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menuButton.setAttribute('aria-expanded','false');navLinks.classList.remove('is-open')}))}
  document.querySelectorAll('[data-disclosure]').forEach(button=>{const panel=document.getElementById(button.dataset.disclosure);if(!panel)return;button.setAttribute('aria-controls',panel.id);button.addEventListener('click',()=>{const expanded=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!expanded));panel.hidden=expanded})});
  const carousel=document.querySelector('.hero-carousel');if(!carousel)return;const slides=[...carousel.querySelectorAll('[data-slide]')],dots=[...carousel.querySelectorAll('[data-carousel-dot]')],previous=carousel.querySelector('[data-carousel-prev]'),next=carousel.querySelector('[data-carousel-next]'),pause=carousel.querySelector('[data-carousel-pause]'),reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)');let active=0,paused=reduceMotion.matches,timer;
  const render=index=>{active=(index+slides.length)%slides.length;slides.forEach((slide,i)=>{const selected=i===active;slide.classList.toggle('is-active',selected);slide.setAttribute('aria-hidden',String(!selected))});dots.forEach((dot,i)=>{const selected=i===active;dot.classList.toggle('is-active',selected);dot.setAttribute('aria-selected',String(selected))})};
  const stop=()=>{window.clearInterval(timer);timer=undefined},start=()=>{stop();if(!paused&&!reduceMotion.matches)timer=window.setInterval(()=>render(active+1),6000)},setPaused=value=>{paused=value;pause.setAttribute('aria-pressed',String(paused));pause.textContent=paused?(document.documentElement.lang==='en'?'Play':'播放'):(document.documentElement.lang==='en'?'Pause':'暫停');start()};
  previous?.addEventListener('click',()=>{render(active-1);start()});next?.addEventListener('click',()=>{render(active+1);start()});dots.forEach((dot,index)=>dot.addEventListener('click',()=>{render(index);start()}));pause?.addEventListener('click',()=>setPaused(!paused));carousel.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'){event.preventDefault();render(active-1);start()}if(event.key==='ArrowRight'){event.preventDefault();render(active+1);start()}});carousel.addEventListener('mouseenter',stop);carousel.addEventListener('mouseleave',start);carousel.addEventListener('focusin',stop);carousel.addEventListener('focusout',event=>{if(!carousel.contains(event.relatedTarget))start()});reduceMotion.addEventListener?.('change',event=>{if(event.matches)setPaused(true)});render(0);start();
})();
